// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt3m_MqGQoFbg_fBlEfNv_520MM5Qmflg',
    appId: '1:284662662077:web:37347858b1dba9b35a88d4',
    messagingSenderId: '284662662077',
    projectId: 'hanppyeom',
    authDomain: 'hanppyeom.firebaseapp.com',
    storageBucket: 'hanppyeom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXSHMQRFpAYdRSqatvok5O9oZ0-MToGg',
    appId: '1:284662662077:android:05137820d13fcb055a88d4',
    messagingSenderId: '284662662077',
    projectId: 'hanppyeom',
    storageBucket: 'hanppyeom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bGjxTc_N6qesgMROllirqgmsVmjePh0',
    appId: '1:284662662077:ios:1949cc1b79407d485a88d4',
    messagingSenderId: '284662662077',
    projectId: 'hanppyeom',
    storageBucket: 'hanppyeom.firebasestorage.app',
    iosBundleId: 'com.hyunsu.hanppyeom',
  );
}
